export type NotificationTemplateInput = { type: 'booking_confirmation'|'payment_instructions'|'partner_reservation'|'cancellation_update'|'transfer_rejected'; notification: { contextNote?: string }; booking: { reference: string; checkIn: string; checkOut: string; totalAmount: number; paymentMethod: string; guestName: string; status: string; guestEmail: string }; property?: { name: string } | null; platformConfig?: { bankName: string; bankAccountName: string; bankAccountNumber: string } | null };
export function shouldSendNotification(status: string) { return status === 'queued'; }
export function buildNotificationTemplate(input: NotificationTemplateInput) { const { type, booking, notification, property, platformConfig } = input; const propertyName = property?.name ?? 'your Menetap stay'; const amount = `Rp ${booking.totalAmount.toLocaleString('en-US')}`; const method = booking.paymentMethod === 'manual_bank_transfer' ? 'manual bank transfer' : 'pay at hotel';
  switch (type) {
    case 'booking_confirmation': return { subject: `Booking confirmed · ${booking.reference}`, text: `Your booking ${booking.reference} at ${propertyName} is confirmed.\nDates: ${booking.checkIn} to ${booking.checkOut}\nTotal: ${amount}\nPayment method: ${method}` };
    case 'payment_instructions': return { subject: `Payment instructions · ${booking.reference}`, text: `Please transfer ${amount} for booking ${booking.reference} to ${platformConfig?.bankName ?? 'Menetap'} / ${platformConfig?.bankAccountName ?? 'PENDING'} / ${platformConfig?.bankAccountNumber ?? 'PENDING'}. Submit your proof in the Confirmation or MyTrips flow.` };
    case 'partner_reservation': return { subject: `New reservation · ${booking.reference}`, text: `A new reservation was made for ${propertyName}.\nReference: ${booking.reference}\nDates: ${booking.checkIn} to ${booking.checkOut}\nGuest: ${booking.guestName}` };
    case 'cancellation_update': return { subject: `Booking update · ${booking.reference}`, text: `Booking ${booking.reference} has a new status: ${booking.status}.` };
    case 'transfer_rejected': return { subject: `Transfer proof needs attention · ${booking.reference}`, text: `Your transfer proof for booking ${booking.reference} could not be verified.\nReason: ${notification.contextNote ?? 'Please review the details and try again.'}\nPlease resubmit through MyTrips.` };
  }
}
