import { mutation, query } from './_generated/server';
import { v } from 'convex/values';
import { requireRole } from './authorization';

const priority = v.union(v.literal('low'), v.literal('normal'), v.literal('high'), v.literal('urgent'));
export const tickets = query({ args: {}, handler: async (ctx) => { const user = await requireRole(ctx, ['partner', 'support', 'operations', 'finance', 'admin']); const properties = user.role === 'partner' ? await ctx.db.query('properties').withIndex('by_owner', (q) => q.eq('ownerUserId', user._id)).collect() : []; const rows:any[]=[]; for (const property of properties) rows.push(...await ctx.db.query('supportTickets').withIndex('by_status', (q) => q.eq('status', 'open')).filter((q) => q.eq(q.field('propertyId'), property._id)).collect()); return user.role === 'partner' ? rows : ctx.db.query('supportTickets').order('desc').take(100); } });
export const createTicket = mutation({ args: { propertyId: v.id('properties'), subject: v.string(), description: v.string(), priority }, handler: async (ctx, args) => { const user = await requireRole(ctx, ['partner']); const property = await ctx.db.get(args.propertyId); if (!property || property.ownerUserId !== user._id) throw new Error('Not authorized for this property.'); const now=Date.now(); const sla=now+(args.priority==='urgent'?15:args.priority==='high'?60:240)*60*1000; return ctx.db.insert('supportTickets',{createdByUserId:user._id,propertyId:args.propertyId,subject:args.subject.trim(),description:args.description.trim(),priority:args.priority,status:'open',slaDueAt:sla,createdAt:now,updatedAt:now}); } });
export const updateTicket = mutation({ args: { ticketId: v.id('supportTickets'), status: v.union(v.literal('open'),v.literal('in_progress'),v.literal('waiting'),v.literal('resolved'),v.literal('closed')), escalationTeam: v.optional(v.union(v.literal('operations'),v.literal('finance'),v.literal('admin'))), note: v.string() }, handler: async (ctx,args)=>{const actor=await requireRole(ctx,['partner','support','operations','finance','admin']);const ticket=await ctx.db.get(args.ticketId);if(!ticket)throw new Error('Ticket not found.');if(actor.role==='partner'){const property=ticket.propertyId?await ctx.db.get(ticket.propertyId):null;if(!property||property.ownerUserId!==actor._id)throw new Error('Not authorized for this ticket.');}const now=Date.now();await ctx.db.patch(ticket._id,{status:args.status,escalationTeam:args.escalationTeam,updatedAt:now});await ctx.db.insert('auditLogs',{actorUserId:actor._id,action:'partner.support_ticket_updated',entityType:'supportTicket',entityId:String(ticket._id),metadata:{status:args.status,team:args.escalationTeam,note:args.note.trim()},createdAt:now,updatedAt:now});return{status:args.status};}});
export const announcements = query({ args: {}, handler: async (ctx)=>{const user=await requireRole(ctx,['partner']);const items=await ctx.db.query('partnerAnnouncements').withIndex('by_active',(q)=>q.eq('active',true)).collect();const reads=await ctx.db.query('partnerAnnouncementReads').withIndex('by_user',(q)=>q.eq('userId',user._id)).collect();const readIds=new Set(reads.map(r=>String(r.announcementId)));return items.map(item=>({...item,read:readIds.has(String(item._id))}));} });
export const markAnnouncementRead = mutation({ args:{announcementId:v.id('partnerAnnouncements')}, handler:async(ctx,args)=>{const user=await requireRole(ctx,['partner']);const existing=await ctx.db.query('partnerAnnouncementReads').withIndex('by_user',(q)=>q.eq('userId',user._id)).filter((q)=>q.eq(q.field('announcementId'),args.announcementId)).first();if(existing)return existing._id;const now=Date.now();return ctx.db.insert('partnerAnnouncementReads',{announcementId:args.announcementId,userId:user._id,readAt:now,createdAt:now,updatedAt:now});} });
export const payoutStatements = query({ args:{propertyId:v.id('properties')}, handler:async(ctx,args)=>{const user=await requireRole(ctx,['partner','finance','operations','admin']);const property=await ctx.db.get(args.propertyId);if(!property||(user.role==='partner'&&property.ownerUserId!==user._id))throw new Error('Not authorized for this property.');return ctx.db.query('payoutStatements').withIndex('by_property',(q)=>q.eq('propertyId',args.propertyId)).order('desc').collect();} });
export const reviewPayout = mutation({ args:{statementId:v.id('payoutStatements'),status:v.union(v.literal('on_hold'),v.literal('ready'),v.literal('paid')),reason:v.string()}, handler:async(ctx,args)=>{const actor=await requireRole(ctx,['finance','operations','admin']);if(args.reason.trim().length<3)throw new Error('Reason is required.');await ctx.db.patch(args.statementId,{status:args.status,reviewedBy:actor._id,holdReason:args.status==='on_hold'?args.reason.trim():undefined,updatedAt:Date.now()});await ctx.db.insert('auditLogs',{actorUserId:actor._id,action:'partner.payout_statement_updated',entityType:'payoutStatement',entityId:String(args.statementId),metadata:{status:args.status,reason:args.reason.trim()},createdAt:Date.now(),updatedAt:Date.now()});return{status:args.status};} });
export const reconciliation = query({ args:{propertyId:v.id('properties')}, handler:async(ctx,args)=>{const user=await requireRole(ctx,['partner','finance','operations','admin']);const property=await ctx.db.get(args.propertyId);if(!property||(user.role==='partner'&&property.ownerUserId!==user._id))throw new Error('Not authorized for this property.');const bookings=await ctx.db.query('bookings').withIndex('by_property',(q)=>q.eq('propertyId',args.propertyId)).collect();const rows=[];for(const booking of bookings){const payment=await ctx.db.query('payments').withIndex('by_booking',(q)=>q.eq('bookingId',booking._id)).first();const refund=await ctx.db.query('refundRequests').withIndex('by_booking',(q)=>q.eq('bookingId',booking._id)).first();rows.push({reference:booking.reference,status:booking.status,gross:booking.totalAmount,paymentStatus:payment?.status||'missing',refundStatus:refund?.status||null});}return rows;} });
