import { mutation, query } from './_generated/server';
import { v } from 'convex/values';
import { auth } from './auth';
import { requireRole } from './authorization';
import { internal } from './_generated/api';

const ownsBooking = async (ctx: any, bookingId: any, email: string) => { const booking = await ctx.db.get(bookingId); const userId = await auth.getUserId(ctx); if (!booking || (userId ? booking.guestUserId !== userId : booking.guestEmail !== email.trim().toLowerCase())) throw new Error('Booking not found.'); return booking; };
export const submitManualTransfer = mutation({ args: { bookingId: v.id('bookings'), reference: v.string(), amount: v.number(), transferredAt: v.string(), evidenceFileId: v.optional(v.id('_storage')), guestEmail: v.string() }, handler: async (ctx, args) => { const booking = await ownsBooking(ctx, args.bookingId, args.guestEmail); if (booking.paymentMethod !== 'manual_bank_transfer') throw new Error('This booking does not use manual bank transfer.'); if (args.amount <= 0 || !args.reference.trim() || !args.transferredAt) throw new Error('Transfer reference, amount, and date are required.'); const existing = await ctx.db.query('manualBankTransfers').withIndex('by_booking', q => q.eq('bookingId', booking._id)).filter(q => q.eq(q.field('status'), 'submitted')).first(); if (existing) return existing._id; const now = Date.now(); await ctx.db.patch(booking._id, { paymentStatus: 'pending_verification', updatedAt: now }); return ctx.db.insert('manualBankTransfers', { bookingId: booking._id, reference: args.reference.trim(), amount: args.amount, transferredAt: args.transferredAt, evidenceFileId: args.evidenceFileId, status: 'submitted', createdAt: now, updatedAt: now }); } });
export const getInstructions = query({ args: { bookingId: v.id('bookings'), guestEmail: v.string() }, handler: async (ctx, args) => { const booking = await ownsBooking(ctx, args.bookingId, args.guestEmail); if (booking.paymentMethod !== 'manual_bank_transfer') throw new Error('This booking does not use manual bank transfer.'); return ctx.db.query('platformConfig').first(); } });
export const listPendingTransfers = query({ args: {}, handler: async ctx => { await requireRole(ctx, ['finance', 'operations', 'admin']); const rows = await ctx.db.query('manualBankTransfers').withIndex('by_status', q => q.eq('status', 'submitted')).order('desc').take(100); return Promise.all(rows.map(async transfer => ({ transfer, booking: await ctx.db.get(transfer.bookingId) }))); } });
export const verifyTransfer = mutation({ args: { transferId: v.id('manualBankTransfers'), decision: v.union(v.literal('approve'), v.literal('reject')), note: v.string() }, handler: async (ctx, args) => { const reviewer = await requireRole(ctx, ['finance', 'operations', 'admin']); const transfer = await ctx.db.get(args.transferId); if (!transfer || transfer.status !== 'submitted') throw new Error('Transfer is no longer pending.'); const booking = await ctx.db.get(transfer.bookingId); if (!booking) throw new Error('Booking not found.'); const now = Date.now(); if (args.decision === 'approve') { await ctx.db.patch(transfer._id, { status: 'verified', reviewedBy: reviewer._id, updatedAt: now }); await ctx.db.patch(booking._id, { paymentStatus: 'paid', updatedAt: now }); const payment = await ctx.db.query('payments').withIndex('by_booking', q => q.eq('bookingId', booking._id)).first(); if (payment) await ctx.db.patch(payment._id, { status: 'paid', updatedAt: now }); await ctx.scheduler.runAfter(0, internal.commissions.calculateForBooking, { bookingId: booking._id }); } else { await ctx.db.patch(transfer._id, { status: 'rejected', reviewedBy: reviewer._id, updatedAt: now }); await ctx.db.patch(booking._id, { paymentStatus: 'unpaid', updatedAt: now }); const notificationId = await ctx.db.insert('bookingNotifications', { bookingId: booking._id, type: 'transfer_rejected', recipientEmail: booking.guestEmail, contextNote: args.note.trim().slice(0, 500), status: 'queued', createdAt: now, updatedAt: now }); await ctx.scheduler.runAfter(0, internal.notifications.send, { notificationId }); } return { status: args.decision }; } });
