import { internalAction, internalMutation, internalQuery, mutation, query } from './_generated/server';
import { v } from 'convex/values';
import { auth } from './auth';
import { requireRole } from './authorization';
import { internal } from './_generated/api';
import { Resend as ResendAPI } from 'resend';

const env = (globalThis as { process?: { env?: Record<string, string | undefined> } }).process?.env ?? {};

export const submitManualTransfer = mutation({ args: { reservationId: v.id('rentalReservations'), reference: v.string(), amount: v.number(), transferredAt: v.string(), evidenceFileId: v.optional(v.id('_storage')) }, handler: async (ctx, args) => { const guestId = await auth.getUserId(ctx); const reservation = await ctx.db.get(args.reservationId); if (!guestId || !reservation || reservation.guestUserId !== guestId) throw new Error('Reservation not found.'); if (args.amount <= 0 || !args.reference.trim() || !args.transferredAt) throw new Error('Transfer reference, amount, and date are required.'); const existing = await ctx.db.query('rentalTransfers').withIndex('by_reservation', q => q.eq('reservationId', reservation._id)).filter(q => q.eq(q.field('status'), 'submitted')).first(); if (existing) return existing._id; const now = Date.now(); await ctx.db.patch(reservation._id, { paymentStatus: 'pending_verification', updatedAt: now }); return ctx.db.insert('rentalTransfers', { reservationId: reservation._id, reference: args.reference.trim(), amount: args.amount, transferredAt: args.transferredAt, evidenceFileId: args.evidenceFileId, status: 'submitted', createdAt: now, updatedAt: now }); } });
export const listPendingTransfers = query({ args: {}, handler: async (ctx) => { await requireRole(ctx, ['finance', 'operations', 'admin']); const rows = await ctx.db.query('rentalTransfers').withIndex('by_status', q => q.eq('status', 'submitted')).order('desc').take(100); return Promise.all(rows.map(async transfer => ({ transfer, reservation: await ctx.db.get(transfer.reservationId) }))); } });
export const verifyTransfer = mutation({ args: { transferId: v.id('rentalTransfers'), decision: v.union(v.literal('approve'), v.literal('reject')), note: v.string() }, handler: async (ctx, args) => { const reviewer = await requireRole(ctx, ['finance', 'operations', 'admin']); const transfer = await ctx.db.get(args.transferId); if (!transfer || transfer.status !== 'submitted') throw new Error('Transfer is no longer pending.'); const reservation = await ctx.db.get(transfer.reservationId); if (!reservation) throw new Error('Reservation not found.'); const now = Date.now(); await ctx.db.patch(transfer._id, { status: args.decision === 'approve' ? 'verified' : 'rejected', reviewedBy: reviewer._id, updatedAt: now }); await ctx.db.patch(reservation._id, { paymentStatus: args.decision === 'approve' ? 'paid' : 'unpaid', updatedAt: now }); if (args.decision === 'reject') { const notificationId = await ctx.db.insert('rentalNotifications', { reservationId: reservation._id, recipientUserId: reservation.guestUserId, type: 'transfer_rejected', contextNote: args.note, createdAt: now, updatedAt: now }); await ctx.scheduler.runAfter(0, internal.rentalPayments.sendRejectedNotification, { notificationId }); } return args.decision; } });
export const getRejectedNotification = internalQuery({ args: { notificationId: v.id('rentalNotifications') }, handler: async (ctx, args) => { const notification = await ctx.db.get(args.notificationId); if (!notification) return null; const user = await ctx.db.get(notification.recipientUserId); return { notification, email: user?.email }; } });
export const markNotificationSent = internalMutation({ args: { notificationId: v.id('rentalNotifications') }, handler: async (ctx, args) => { await ctx.db.patch(args.notificationId, { updatedAt: Date.now() }); } });
export const sendRejectedNotification = internalAction({ args: { notificationId: v.id('rentalNotifications') }, handler: async (ctx, args) => { const payload = await ctx.runQuery(internal.rentalPayments.getRejectedNotification, args); if (!payload?.email) return { skipped: true }; const resend = new ResendAPI(env.AUTH_RESEND_KEY); const { error } = await resend.emails.send({ from: env.AUTH_RESEND_FROM ?? 'Menetap <onboarding@resend.dev>', to: [payload.email], subject: 'Rental transfer needs attention', text: payload.notification.contextNote }); if (error) throw new Error(error.message); await ctx.runMutation(internal.rentalPayments.markNotificationSent, args); return { sent: true }; } });
