import { mutation, query } from './_generated/server';
import { v } from 'convex/values';
import { auth } from './auth';
import { requireRole } from './authorization';
const reservationStatus = v.union(v.literal('reserved'), v.literal('confirmed'), v.literal('delivered'), v.literal('returned'), v.literal('cancelled'));
const day = (value: string) => new Date(`${value}T00:00:00Z`);
export function rentalTotal(dailyRate: number, deliveryDate: string, returnDate: string, driverSurcharge = 0, deliverySurcharge = 0, driverIncluded = false, deliveryIncluded = false) { const days = Math.ceil((day(returnDate).getTime() - day(deliveryDate).getTime()) / 86400000); return { days, total: dailyRate * days + (driverIncluded ? driverSurcharge * days : 0) + (deliveryIncluded ? deliverySurcharge : 0) }; }
export function rentalDatesWithinBooking(deliveryDate: string, returnDate: string, checkIn: string, checkOut: string) { const delivery = day(deliveryDate); const returned = day(returnDate); const checkInDate = day(checkIn); const checkOutDate = day(checkOut); return returned > delivery && delivery >= new Date(checkInDate.getTime() - 86400000) && delivery <= checkInDate && returned >= checkOutDate && returned <= new Date(checkOutDate.getTime() + 86400000); }
export const create = mutation({ args: { bookingId: v.id('bookings'), vehicleId: v.id('vehicles'), deliveryDate: v.string(), returnDate: v.string(), driverIncluded: v.boolean(), deliveryIncluded: v.boolean() }, handler: async (ctx, args) => { const guestId = await auth.getUserId(ctx); const booking = await ctx.db.get(args.bookingId); if (!guestId || !booking || booking.guestUserId !== guestId) throw new Error('Booking not found for this account.'); if (booking.status !== 'confirmed') throw new Error('Rentals can only be added to a confirmed stay.'); if (booking.checkOut < new Date().toISOString().slice(0, 10)) throw new Error('This stay has already ended and cannot accept a rental.'); if (!rentalDatesWithinBooking(args.deliveryDate, args.returnDate, booking.checkIn, booking.checkOut)) throw new Error('Rental delivery and return dates must stay within one day of your confirmed stay.'); const vehicle = await ctx.db.get(args.vehicleId); if (!vehicle || !vehicle.active) throw new Error('Vehicle is unavailable.'); const pricing = rentalTotal(vehicle.dailyRate, args.deliveryDate, args.returnDate, vehicle.driverSurcharge, vehicle.deliverySurcharge, args.driverIncluded, args.deliveryIncluded); if (pricing.days < 1) throw new Error('Rental dates must include at least one day.'); const availability = await ctx.db.query('vehicleAvailability').withIndex('by_vehicle_date', (q) => q.eq('vehicleId', vehicle._id).gte('date', args.deliveryDate).lt('date', args.returnDate)).collect(); if (availability.length !== pricing.days || availability.some((entry) => entry.availableUnits < 1)) throw new Error('Vehicle is not available for every requested rental day.'); const now = Date.now(); for (const entry of availability) await ctx.db.patch(entry._id, { availableUnits: entry.availableUnits - 1, updatedAt: now }); const reservationId = await ctx.db.insert('rentalReservations', { bookingId: booking._id, guestUserId: guestId, vehicleId: vehicle._id, deliveryDate: args.deliveryDate, returnDate: args.returnDate, driverIncluded: args.driverIncluded, deliveryIncluded: args.deliveryIncluded, totalAmount: pricing.total, currency: vehicle.currency, status: 'reserved', paymentStatus: 'unpaid', createdAt: now, updatedAt: now }); return { reservationId, totalAmount: pricing.total }; } });
export const listMine = query({ args: {}, handler: async (ctx) => { const guestId = await auth.getUserId(ctx); if (!guestId) return []; const rows = await ctx.db.query('rentalReservations').withIndex('by_guest', (q) => q.eq('guestUserId', guestId)).order('desc').collect(); return Promise.all(rows.map(async (row) => ({ ...row, vehicle: await ctx.db.get(row.vehicleId) }))); } });
export const listForAdmin = query({ args: {}, handler: async (ctx) => { await requireRole(ctx, ['admin', 'operations']); const rows = await ctx.db.query('rentalReservations').order('desc').take(100); return Promise.all(rows.map(async (row) => ({ reservation: row, vehicle: await ctx.db.get(row.vehicleId), booking: await ctx.db.get(row.bookingId) }))); } });
export const updateStatus = mutation({ args: { reservationId: v.id('rentalReservations'), status: reservationStatus }, handler: async (ctx, args) => { await requireRole(ctx, ['admin']); const reservation = await ctx.db.get(args.reservationId); if (!reservation) throw new Error('Reservation not found.'); await ctx.db.patch(reservation._id, { status: args.status, updatedAt: Date.now() }); return args.status; } });
