import { defineSchema, defineTable } from 'convex/server';
import { v } from 'convex/values';

const timestamps = { createdAt: v.number(), updatedAt: v.number() };

export default defineSchema({
  users: defineTable({ email: v.string(), name: v.optional(v.string()), role: v.union(v.literal('guest'), v.literal('partner'), v.literal('vendor'), v.literal('support'), v.literal('operations'), v.literal('finance'), v.literal('admin')), status: v.union(v.literal('active'), v.literal('pending'), v.literal('suspended')), ...timestamps }).index('by_email', ['email']).index('by_role', ['role']),
  properties: defineTable({ name: v.string(), type: v.union(v.literal('hotel'), v.literal('villa'), v.literal('guesthouse'), v.literal('homestay')), segment: v.optional(v.union(v.literal('budget'), v.literal('midscale'), v.literal('upscale'), v.literal('boutique'))), description: v.string(), address: v.string(), area: v.string(), city: v.string(), country: v.string(), status: v.union(v.literal('draft'), v.literal('verification'), v.literal('approved'), v.literal('published'), v.literal('suspended')), ownerUserId: v.optional(v.id('users')), verifiedAt: v.optional(v.number()), ...timestamps }).index('by_status', ['status']).index('by_area', ['area']).index('by_owner', ['ownerUserId']),
  roomTypes: defineTable({ propertyId: v.id('properties'), name: v.string(), description: v.string(), maxGuests: v.number(), totalUnits: v.number(), amenities: v.array(v.string()), active: v.boolean(), ...timestamps }).index('by_property', ['propertyId']),
  ratePlans: defineTable({ propertyId: v.id('properties'), roomTypeId: v.id('roomTypes'), name: v.string(), price: v.number(), currency: v.string(), includes: v.array(v.string()), cancellationPolicy: v.string(), active: v.boolean(), ...timestamps }).index('by_room_type', ['roomTypeId']).index('by_property', ['propertyId']),
  availability: defineTable({ propertyId: v.id('properties'), roomTypeId: v.id('roomTypes'), date: v.string(), totalUnits: v.number(), availableUnits: v.number(), rate: v.number(), status: v.union(v.literal('open'), v.literal('closed')), ...timestamps }).index('by_room_date', ['roomTypeId', 'date']).index('by_property_date', ['propertyId', 'date']),
  bookings: defineTable({ reference: v.string(), guestUserId: v.optional(v.id('users')), propertyId: v.id('properties'), roomTypeId: v.id('roomTypes'), checkIn: v.string(), checkOut: v.string(), guestCount: v.number(), guestName: v.string(), guestEmail: v.string(), totalAmount: v.number(), currency: v.string(), status: v.union(v.literal('pending'), v.literal('confirmed'), v.literal('cancelled'), v.literal('completed'), v.literal('no_show')), paymentMethod: v.union(v.literal('pay_at_hotel'), v.literal('manual_bank_transfer')), paymentStatus: v.union(v.literal('unpaid'), v.literal('pending_verification'), v.literal('paid'), v.literal('refunded')), ...timestamps }).index('by_reference', ['reference']).index('by_guest', ['guestUserId']).index('by_property', ['propertyId']).index('by_status', ['status']),
  payments: defineTable({ bookingId: v.id('bookings'), method: v.union(v.literal('pay_at_hotel'), v.literal('manual_bank_transfer')), amount: v.number(), currency: v.string(), status: v.union(v.literal('unpaid'), v.literal('pending_verification'), v.literal('paid'), v.literal('refunded')), ...timestamps }).index('by_booking', ['bookingId']),
  manualBankTransfers: defineTable({ bookingId: v.id('bookings'), reference: v.string(), amount: v.number(), transferredAt: v.string(), evidenceFileId: v.optional(v.id('_storage')), status: v.union(v.literal('submitted'), v.literal('verified'), v.literal('rejected')), reviewedBy: v.optional(v.id('users')), ...timestamps }).index('by_booking', ['bookingId']).index('by_status', ['status']),
  addOnServices: defineTable({ name: v.string(), category: v.union(v.literal('airport_shuttle'), v.literal('train_transfer'), v.literal('breakfast'), v.literal('early_check_in'), v.literal('late_check_out'), v.literal('travel_insurance')), description: v.string(), providerName: v.string(), price: v.number(), currency: v.string(), active: v.boolean(), ...timestamps }).index('by_category', ['category']).index('by_active', ['active']),
  bookingAddOns: defineTable({ bookingId: v.id('bookings'), serviceId: v.id('addOnServices'), quantity: v.number(), amount: v.number(), status: v.union(v.literal('requested'), v.literal('confirmed'), v.literal('fulfilled'), v.literal('cancelled')), ...timestamps }).index('by_booking', ['bookingId']).index('by_service', ['serviceId']),
  commissions: defineTable({ bookingId: v.id('bookings'), propertyId: v.id('properties'), ratePercent: v.number(), amount: v.number(), currency: v.string(), status: v.union(v.literal('pending'), v.literal('calculated'), v.literal('settled'), v.literal('voided')), ...timestamps }).index('by_booking', ['bookingId']).index('by_property', ['propertyId']).index('by_status', ['status']),
  supportTickets: defineTable({ createdByUserId: v.optional(v.id('users')), bookingId: v.optional(v.id('bookings')), propertyId: v.optional(v.id('properties')), subject: v.string(), description: v.string(), priority: v.union(v.literal('low'), v.literal('normal'), v.literal('high'), v.literal('urgent')), status: v.union(v.literal('open'), v.literal('in_progress'), v.literal('waiting'), v.literal('resolved'), v.literal('closed')), assignedToUserId: v.optional(v.id('users')), ...timestamps }).index('by_status', ['status']).index('by_booking', ['bookingId']).index('by_assignee', ['assignedToUserId']),
  auditLogs: defineTable({ actorUserId: v.optional(v.id('users')), action: v.string(), entityType: v.string(), entityId: v.string(), metadata: v.optional(v.any()), ...timestamps }).index('by_entity', ['entityType', 'entityId']).index('by_actor', ['actorUserId']),
});
