import { defineSchema, defineTable } from 'convex/server';
import { v } from 'convex/values';
import { authTables } from '@convex-dev/auth/server';

const timestamps = { createdAt: v.number(), updatedAt: v.number() };
const { users: _authUsers, ...authSchema } = authTables;
void _authUsers;

export default defineSchema({
  ...authSchema,
  users: defineTable({
    email: v.optional(v.string()), name: v.optional(v.string()), image: v.optional(v.string()),
    emailVerificationTime: v.optional(v.number()), phone: v.optional(v.string()), phoneVerificationTime: v.optional(v.number()), isAnonymous: v.optional(v.boolean()),
    role: v.union(v.literal('guest'), v.literal('partner'), v.literal('vendor'), v.literal('support'), v.literal('operations'), v.literal('finance'), v.literal('admin')),
    status: v.union(v.literal('active'), v.literal('pending'), v.literal('suspended')), ...timestamps,
  }).index('email', ['email']).index('by_role', ['role']),
  savedStays: defineTable({ userId: v.id('users'), propertyId: v.id('properties'), ...timestamps }).index('by_user', ['userId']).index('by_user_property', ['userId', 'propertyId']),
  properties: defineTable({ name: v.string(), type: v.union(v.literal('hotel'), v.literal('villa'), v.literal('guesthouse'), v.literal('homestay')), segment: v.optional(v.union(v.literal('budget'), v.literal('midscale'), v.literal('upscale'), v.literal('boutique'))), description: v.string(), address: v.string(), area: v.string(), city: v.string(), country: v.string(), status: v.union(v.literal('draft'), v.literal('verification'), v.literal('approved'), v.literal('published'), v.literal('suspended')), ownerUserId: v.optional(v.id('users')), verifiedAt: v.optional(v.number()), ...timestamps }).index('by_status', ['status']).index('by_area', ['area']).index('by_owner', ['ownerUserId']),
  roomTypes: defineTable({ propertyId: v.id('properties'), name: v.string(), description: v.string(), maxGuests: v.number(), totalUnits: v.number(), amenities: v.array(v.string()), active: v.boolean(), childPolicy: v.optional(v.object({ acceptsChildren: v.boolean(), maxChildAge: v.number(), pricing: v.union(v.literal('free'), v.literal('flat'), v.literal('age_band')), flatRate: v.optional(v.number()), ageRates: v.optional(v.array(v.object({ maxAge: v.number(), nightlyRate: v.number() }))) })), ...timestamps }).index('by_property', ['propertyId']),
  ratePlans: defineTable({ propertyId: v.id('properties'), roomTypeId: v.id('roomTypes'), name: v.string(), price: v.number(), currency: v.string(), includes: v.array(v.string()), cancellationPolicy: v.string(), active: v.boolean(), ...timestamps }).index('by_room_type', ['roomTypeId']).index('by_property', ['propertyId']),
  availability: defineTable({ propertyId: v.id('properties'), roomTypeId: v.id('roomTypes'), date: v.string(), totalUnits: v.number(), availableUnits: v.number(), rate: v.number(), status: v.union(v.literal('open'), v.literal('closed')), ...timestamps }).index('by_room_date', ['roomTypeId', 'date']).index('by_property_date', ['propertyId', 'date']),
  inventoryHolds: defineTable({ token: v.string(), propertyId: v.id('properties'), roomTypeId: v.id('roomTypes'), checkIn: v.string(), checkOut: v.string(), quantity: v.number(), expiresAt: v.number(), status: v.union(v.literal('active'), v.literal('converted'), v.literal('released'), v.literal('expired')), ...timestamps }).index('by_token', ['token']).index('by_expiry', ['status', 'expiresAt']).index('by_room', ['roomTypeId']),
  bookings: defineTable({ reference: v.string(), idempotencyKey: v.optional(v.string()), guestUserId: v.optional(v.id('users')), propertyId: v.id('properties'), roomTypeId: v.id('roomTypes'), checkIn: v.string(), checkOut: v.string(), guestCount: v.number(), childAges: v.optional(v.array(v.number())), childPolicySnapshot: v.optional(v.any()), guestName: v.string(), guestEmail: v.string(), totalAmount: v.number(), currency: v.string(), status: v.union(v.literal('pending'), v.literal('confirmed'), v.literal('cancelled'), v.literal('completed'), v.literal('no_show')), paymentMethod: v.union(v.literal('pay_at_hotel'), v.literal('manual_bank_transfer')), paymentStatus: v.union(v.literal('unpaid'), v.literal('pending_verification'), v.literal('paid'), v.literal('refunded')), ...timestamps }).index('by_reference', ['reference']).index('by_idempotency', ['idempotencyKey']).index('by_guest', ['guestUserId']).index('by_property', ['propertyId']).index('by_status', ['status']),
  bookingStatusHistory: defineTable({ bookingId: v.id('bookings'), fromStatus: v.optional(v.string()), toStatus: v.string(), reason: v.optional(v.string()), changedByUserId: v.optional(v.id('users')), ...timestamps }).index('by_booking', ['bookingId']),
  bookingRooms: defineTable({ bookingId: v.id('bookings'), roomTypeId: v.id('roomTypes'), roomName: v.string(), quantity: v.number(), ratePlan: v.string(), roomAmount: v.number(), breakfastAmount: v.number(), ...timestamps }).index('by_booking', ['bookingId']),
  payments: defineTable({ bookingId: v.id('bookings'), method: v.union(v.literal('pay_at_hotel'), v.literal('manual_bank_transfer')), amount: v.number(), currency: v.string(), status: v.union(v.literal('unpaid'), v.literal('pending_verification'), v.literal('paid'), v.literal('refunded')), ...timestamps }).index('by_booking', ['bookingId']),
  bookingNotifications: defineTable({ bookingId: v.id('bookings'), type: v.union(v.literal('booking_confirmation'), v.literal('payment_instructions'), v.literal('partner_reservation'), v.literal('cancellation_update')), recipientEmail: v.string(), status: v.union(v.literal('queued'), v.literal('sent'), v.literal('failed')), providerId: v.optional(v.string()), error: v.optional(v.string()), sentAt: v.optional(v.number()), ...timestamps }).index('by_booking', ['bookingId']).index('by_status', ['status']),
  refundRequests: defineTable({ bookingId: v.id('bookings'), amount: v.number(), reason: v.string(), status: v.union(v.literal('pending'), v.literal('approved'), v.literal('rejected'), v.literal('processed')), reviewedByUserId: v.optional(v.id('users')), reviewedAt: v.optional(v.number()), ...timestamps }).index('by_booking', ['bookingId']).index('by_status', ['status']),
  manualBankTransfers: defineTable({ bookingId: v.id('bookings'), reference: v.string(), amount: v.number(), transferredAt: v.string(), evidenceFileId: v.optional(v.id('_storage')), status: v.union(v.literal('submitted'), v.literal('verified'), v.literal('rejected')), reviewedBy: v.optional(v.id('users')), ...timestamps }).index('by_booking', ['bookingId']).index('by_status', ['status']),
  addOnServices: defineTable({ name: v.string(), category: v.union(v.literal('airport_shuttle'), v.literal('train_transfer'), v.literal('breakfast'), v.literal('early_check_in'), v.literal('late_check_out'), v.literal('travel_insurance')), description: v.string(), providerName: v.string(), price: v.number(), currency: v.string(), active: v.boolean(), ...timestamps }).index('by_category', ['category']).index('by_active', ['active']),
  bookingAddOns: defineTable({ bookingId: v.id('bookings'), serviceId: v.id('addOnServices'), quantity: v.number(), amount: v.number(), status: v.union(v.literal('requested'), v.literal('confirmed'), v.literal('fulfilled'), v.literal('cancelled')), ...timestamps }).index('by_booking', ['bookingId']).index('by_service', ['serviceId']),
  supportRequests: defineTable({ name: v.string(), email: v.string(), bookingReference: v.optional(v.string()), message: v.string(), status: v.union(v.literal('open'), v.literal('in_progress'), v.literal('resolved')), ...timestamps }).index('by_email', ['email']).index('by_status', ['status']),
  commissions: defineTable({ bookingId: v.id('bookings'), propertyId: v.id('properties'), ratePercent: v.number(), amount: v.number(), currency: v.string(), status: v.union(v.literal('pending'), v.literal('calculated'), v.literal('settled'), v.literal('voided')), ...timestamps }).index('by_booking', ['bookingId']).index('by_property', ['propertyId']).index('by_status', ['status']),
  supportTickets: defineTable({ createdByUserId: v.optional(v.id('users')), bookingId: v.optional(v.id('bookings')), propertyId: v.optional(v.id('properties')), subject: v.string(), description: v.string(), priority: v.union(v.literal('low'), v.literal('normal'), v.literal('high'), v.literal('urgent')), status: v.union(v.literal('open'), v.literal('in_progress'), v.literal('waiting'), v.literal('resolved'), v.literal('closed')), assignedToUserId: v.optional(v.id('users')), ...timestamps }).index('by_status', ['status']).index('by_booking', ['bookingId']).index('by_assignee', ['assignedToUserId']),
  auditLogs: defineTable({ actorUserId: v.optional(v.id('users')), action: v.string(), entityType: v.string(), entityId: v.string(), metadata: v.optional(v.any()), ...timestamps }).index('by_entity', ['entityType', 'entityId']).index('by_actor', ['actorUserId']),
});
