import { mutation, query } from './_generated/server';
import { v } from 'convex/values';
import { requireRole } from './authorization';

const category = v.union(v.literal('linen'), v.literal('housekeeping'), v.literal('guest_amenities'), v.literal('stationery'));
export function projectActiveProduct(product: { _id: any; name: string; description?: string; unit: string; price: number; currency: string; category: string; vendorId?: unknown }) { const { vendorId: _vendorId, ...safe } = product; return safe; }
export const listMine = query({ args: {}, handler: async (ctx) => { const user = await requireRole(ctx, ['vendor']); return ctx.db.query('supplierProducts').withIndex('by_vendor', (q) => q.eq('vendorId', user._id)).order('desc').collect(); } });
export const create = mutation({ args: { name: v.string(), description: v.optional(v.string()), unit: v.string(), price: v.number(), currency: v.string(), category }, handler: async (ctx, args) => { const user = await requireRole(ctx, ['vendor']); if (args.price <= 0 || args.name.trim().length < 2) throw new Error('Product name and positive price are required.'); const now = Date.now(); return ctx.db.insert('supplierProducts', { ...args, name: args.name.trim(), unit: args.unit.trim(), currency: args.currency.trim(), vendorId: user._id, moderationStatus: 'pending', active: true, createdAt: now, updatedAt: now }); } });
export const update = mutation({ args: { productId: v.id('supplierProducts'), name: v.string(), description: v.optional(v.string()), unit: v.string(), price: v.number(), currency: v.string(), category, active: v.boolean() }, handler: async (ctx, args) => { const user = await requireRole(ctx, ['vendor']); const product = await ctx.db.get(args.productId); if (!product || product.vendorId !== user._id) throw new Error('Not authorized for this product.'); const changed = product.name !== args.name.trim() || product.description !== args.description || product.price !== args.price || product.category !== args.category; const now = Date.now(); const { productId: _productId, ...updates } = args; await ctx.db.patch(product._id, { ...updates, name: args.name.trim(), unit: args.unit.trim(), currency: args.currency.trim(), moderationStatus: changed ? 'pending' : product.moderationStatus, rejectionReason: changed ? undefined : product.rejectionReason, updatedAt: now }); return product._id; } });
export const listPendingModeration = query({ args: {}, handler: async (ctx) => { await requireRole(ctx, ['operations', 'admin']); const products = await ctx.db.query('supplierProducts').withIndex('by_moderation', (q) => q.eq('moderationStatus', 'pending')).collect(); return Promise.all(products.map(async (product) => ({ product, vendor: await ctx.db.get(product.vendorId) }))); } });
export const moderate = mutation({ args: { productId: v.id('supplierProducts'), status: v.union(v.literal('approved'), v.literal('rejected')), rejectionReason: v.optional(v.string()) }, handler: async (ctx, args) => { const user = await requireRole(ctx, ['operations', 'admin']); const product = await ctx.db.get(args.productId); if (!product) throw new Error('Product not found.'); if (args.status === 'rejected' && !args.rejectionReason?.trim()) throw new Error('A rejection reason is required.'); await ctx.db.patch(product._id, { moderationStatus: args.status, rejectionReason: args.status === 'rejected' ? args.rejectionReason?.trim() : undefined, updatedAt: Date.now() }); return { reviewedBy: user._id, status: args.status }; } });
export const listActive = query({ args: {}, handler: async (ctx) => { await requireRole(ctx, ['partner', 'operations', 'admin']); const products = await ctx.db.query('supplierProducts').withIndex('by_moderation', (q) => q.eq('moderationStatus', 'approved')).collect(); return products.filter((product) => product.active).map(projectActiveProduct); } });
