import { mutation, query } from './_generated/server';
import { v } from 'convex/values';
import { requireRole } from './authorization';

const status = v.union(v.literal('placed'), v.literal('confirmed'), v.literal('shipped'), v.literal('delivered'), v.literal('cancelled'));
export function calculateSupplyTotal(products: Array<{ id: string; price: number }>, lines: Array<{ id: string; quantity: number }>) { return lines.reduce((total, line) => total + (products.find((product) => product.id === line.id)?.price ?? 0) * line.quantity, 0); }
export const create = mutation({ args: { propertyId: v.id('properties'), items: v.array(v.object({ supplierProductId: v.id('supplierProducts'), quantity: v.number() })), deliveryAddress: v.string(), notes: v.optional(v.string()) }, handler: async (ctx, args) => { const user = await requireRole(ctx, ['partner']); const property = await ctx.db.get(args.propertyId); if (!property || property.ownerUserId !== user._id) throw new Error('Not authorized for this property.'); if (!args.items.length || !args.deliveryAddress.trim()) throw new Error('Order items and delivery address are required.'); const now = Date.now(); const resolved = await Promise.all(args.items.map(async (line) => { if (!Number.isInteger(line.quantity) || line.quantity < 1) throw new Error('Quantities must be positive whole numbers.'); const product = await ctx.db.get(line.supplierProductId); if (!product || product.moderationStatus !== 'approved' || !product.active) throw new Error('Product is unavailable.'); const lineAmount = product.price * line.quantity; return { product, quantity: line.quantity, lineAmount }; })); const totalAmount = resolved.reduce((sum, line) => sum + line.lineAmount, 0); const reference = `SUP-${new Date(now).toISOString().slice(0,10).replaceAll('-','')}-${Math.random().toString(36).slice(2,8).toUpperCase()}`; const orderId = await ctx.db.insert('supplyOrders', { propertyId: args.propertyId, placedByUserId: user._id, reference, totalAmount, currency: 'IDR', status: 'placed', paymentStatus: 'unpaid', deliveryAddress: args.deliveryAddress.trim(), notes: args.notes?.trim(), createdAt: now, updatedAt: now }); for (const line of resolved) await ctx.db.insert('supplyOrderItems', { supplyOrderId: orderId, supplierProductId: line.product._id, vendorId: line.product.vendorId, productName: line.product.name, unit: line.product.unit, quantity: line.quantity, unitPrice: line.product.price, lineAmount: line.lineAmount, createdAt: now, updatedAt: now }); return { orderId, reference, totalAmount }; } });
export const listForProperty = query({ args: { propertyId: v.id('properties') }, handler: async (ctx, args) => { const user = await requireRole(ctx, ['partner']); const property = await ctx.db.get(args.propertyId); if (!property || property.ownerUserId !== user._id) throw new Error('Not authorized for this property.'); const orders = await ctx.db.query('supplyOrders').withIndex('by_property', (q) => q.eq('propertyId', args.propertyId)).order('desc').collect(); return Promise.all(orders.map(async (order) => ({ ...order, items: (await ctx.db.query('supplyOrderItems').withIndex('by_order', (q) => q.eq('supplyOrderId', order._id)).collect()).map(({ _id, supplyOrderId, supplierProductId, productName, unit, quantity, unitPrice, lineAmount, createdAt, updatedAt }) => ({ _id, supplyOrderId, supplierProductId, productName, unit, quantity, unitPrice, lineAmount, createdAt, updatedAt })) }))); } });
export const updateStatus = mutation({ args: { orderId: v.id('supplyOrders'), status, reason: v.optional(v.string()) }, handler: async (ctx, args) => { await requireRole(ctx, ['operations', 'admin']); const order = await ctx.db.get(args.orderId); if (!order) throw new Error('Order not found.'); await ctx.db.patch(order._id, { status: args.status, updatedAt: Date.now() }); return { status: args.status }; } });
export const listForAdmin = query({ args: {}, handler: async (ctx) => { await requireRole(ctx, ['operations', 'admin']); return ctx.db.query('supplyOrders').order('desc').take(100); } });
