import { useState } from 'react';
import { useMutation, useQuery } from 'convex/react';
import { api } from '../convex/_generated/api';
import type { GuestScreen, SearchState } from './types';
import { AuthPanel } from './auth';
import { useAuthActions, useConvexAuth } from '@convex-dev/auth/react';

const initialSearch: SearchState = { destination: 'Greater Yogyakarta', checkIn: '', checkOut: '', guests: 2 };

export function App() {
  const [screen, setScreen] = useState<GuestScreen>('home');
  const [search, setSearch] = useState(initialSearch);
  const [selectedProperty, setSelectedProperty] = useState<string | null>(null);
  const [selectedRoom, setSelectedRoom] = useState<string | null>(null);
  const [bookingCode, setBookingCode] = useState<string | null>(null);
  const [authOpen, setAuthOpen] = useState(false);
  if (authOpen) return <div className="app-shell"><AuthPanel onClose={() => setAuthOpen(false)} /></div>;
  return <div className="app-shell"><Header onHome={() => setScreen('home')} onAuth={() => setAuthOpen(true)} />
    {screen === 'home' && <Home search={search} setSearch={setSearch} onSearch={() => setScreen('search')} />}
    {screen === 'search' && <SearchResults search={search} onBack={() => setScreen('home')} onSelect={(id) => { setSelectedProperty(id); setScreen('hotel'); }} />}
    {screen === 'hotel' && <HotelDetail propertyId={selectedProperty} onBack={() => setScreen('search')} onRooms={() => setScreen('rooms')} />}
    {screen === 'rooms' && <RoomSelection propertyId={selectedProperty} onBack={() => setScreen('hotel')} onContinue={(id) => { setSelectedRoom(id); setScreen('checkout'); }} />}
    {screen === 'checkout' && <Checkout propertyId={selectedProperty} roomTypeId={selectedRoom} search={search} onBack={() => setScreen('rooms')} onComplete={(code) => { setBookingCode(code); setScreen('confirmation'); }} />}
    {screen === 'confirmation' && <Confirmation code={bookingCode} onHome={() => setScreen('home')} />}
  </div>;
}

function Header({ onHome, onAuth }: { onHome: () => void; onAuth: () => void }) { const { isAuthenticated } = useConvexAuth(); const { signOut } = useAuthActions(); return <header className="nav"><button className="wordmark nav-button" onClick={onHome}>menetap<span>.</span></button><nav><button onClick={onHome}>Stays</button><button onClick={onHome}>Rentals</button><button onClick={onHome}>Experiences</button><button onClick={onHome}>Rewards</button></nav><div className="nav-actions">{isAuthenticated ? <button onClick={() => void signOut()}>Log out</button> : <><button onClick={onAuth}>Log in</button><button className="outline-button" onClick={onAuth}>Sign up</button></>}</div></header>; }

function Home({ search, setSearch, onSearch }: { search: SearchState; setSearch: (value: SearchState) => void; onSearch: () => void }) { return <main><section className="hero"><p className="eyebrow">Curated stays in Indonesia</p><h1>Find your stay.<br /><em>Stay better.</em></h1><p className="hero-copy">Transparent prices, carefully selected properties, and everything you need around the stay.</p><SearchBar search={search} setSearch={setSearch} onSearch={onSearch} /></section><section className="section"><div className="section-heading"><div><p className="eyebrow">Popular across Indonesia right now</p><h2>Stay somewhere worth remembering.</h2></div><span className="muted">Curated by Menetap</span></div><div className="destination-pills">{['Yogyakarta', 'Bandung', 'Semarang', 'Malang', 'Solo', 'Surabaya', 'Bali', 'Jakarta'].map((city) => <button key={city} className="pill" onClick={onSearch}>{city}</button>)}</div><div className="feature-grid"><FeatureCard title="Curated, not crowded" text="Every property is reviewed for accuracy, cleanliness, and a better stay experience." /><FeatureCard title="Real prices" text="What you see is what you pay. No inflated rates or surprise fees at checkout." /><FeatureCard title="Everything around the stay" text="Add breakfast, transfers, early check-in, and more when you need them." /></div></section><TrustStrip /><FeaturedSection /><PricingSection /><ExperienceSection /><Footer /></main>; }

function TrustStrip() { return <section className="trust-strip"><span>✓ Verified reviews only</span><span>✓ Instant confirmation</span><span>↻ Flexible cancellation</span><span>✦ Menetap Rewards on every stay</span></section>; }
function FeaturedSection() { const stays = [['Kaliurang Heritage Villa', 'Sleman, Yogyakarta', 'Rp 890,000', '4.8'], ['Prawirotaman Boutique', 'Mergangsan, Yogyakarta', 'Rp 620,000', '4.6'], ['Malioboro Skyline Suites', 'Gedong Tengen, Yogyakarta', 'Rp 1,100,000', '4.9']]; return <section className="section"><div className="section-heading"><h2>Featured in Yogyakarta</h2><span className="muted">See all stays →</span></div><div className="stay-grid">{stays.map(([name, area, price, rating]) => <article className="stay-card" key={name}><div className="stay-photo">Hotel photo</div><div className="stay-content"><div className="stay-title"><div><h3>{name}</h3><p>{area}</p></div><span className="rating">★ {rating}</span></div><div className="tags"><span>Free cancellation</span><span>Breakfast incl.</span></div><strong>{price}<small>/night</small></strong></div></article>)}</div></section>; }
function PricingSection() { return <section className="pricing-section"><div><p className="eyebrow">Why Menetap</p><h2>The price you see is the price you pay.</h2><p className="muted">Every rate is checked against real market data. No hidden service fees—the total you see at search is your total at checkout.</p><a href="#pricing">Learn how pricing works →</a></div><div className="rate-card"><div className="rate-heading"><span>Rate breakdown</span><b>Live pricing</b></div><div className="rate-row"><span>Market average</span><strong>Rp 980,000</strong></div><div className="rate-row"><span>Menetap rate</span><strong className="violet">Rp 890,000</strong></div><div className="rate-total"><span>Total tonight</span><strong>Rp 890,000</strong></div><div className="rate-bar"><i /></div><small>9% below Yogyakarta market average today — no fees added later</small></div></section>; }
function ExperienceSection() { return <section className="section"><div className="section-heading"><h2>Add local experiences</h2><span className="muted">See all →</span></div><div className="experience-grid">{[['Borobudur sunrise tour', 'Rp 350,000/person'], ['Merapi jeep adventure', 'Rp 275,000/person'], ['Javanese cooking class', 'Rp 220,000/person'], ['Prambanan at sunset', 'Rp 180,000/person']].map(([name, price]) => <article className="experience-card" key={name}><div className="experience-photo">Photo</div><div><strong>{name}</strong><small>From {price}</small></div></article>)}</div></section>; }
function Footer() { return <footer><div className="footer-brand"><span className="wordmark">menetap<span>.</span></span><p>More than a room. Everything around the stay.</p></div><div><strong>Explore</strong><a href="#stays">Stays</a><a href="#rentals">Rentals</a><a href="#experiences">Experiences</a></div><div><strong>For partners</strong><a href="#list">List your property</a><a href="#services">Partner services</a><a href="#support">Help center</a></div><div><strong>Managed by</strong><a href="https://upscale.asia">UPSCALE</a><a href="#privacy">Privacy</a><a href="#terms">Terms</a></div></footer>; }

function SearchBar({ search, setSearch, onSearch }: { search: SearchState; setSearch: (value: SearchState) => void; onSearch: () => void }) { return <div className="search-card"><label>Where are you going?<input value={search.destination} onChange={(e) => setSearch({ ...search, destination: e.target.value })} placeholder="Greater Yogyakarta" /></label><label>Check in<input value={search.checkIn} onChange={(e) => setSearch({ ...search, checkIn: e.target.value })} placeholder="Add dates" /></label><label>Check out<input value={search.checkOut} onChange={(e) => setSearch({ ...search, checkOut: e.target.value })} placeholder="Add dates" /></label><label>Guests<input type="number" min="1" value={search.guests} onChange={(e) => setSearch({ ...search, guests: Number(e.target.value) })} /></label><button onClick={onSearch}>Search stays</button></div>; }

function SearchResults({ search, onBack, onSelect }: { search: SearchState; onBack: () => void; onSelect: (id: string) => void }) { const properties = useQuery(api.properties.listPublished, { area: search.destination }); return <main className="page"><button className="back-button" onClick={onBack}>← Back</button><div className="page-heading"><div><p className="eyebrow">Search results</p><h2>Stays in {search.destination}</h2><p className="muted">Curated properties with transparent pricing.</p></div><span className="result-count">{properties?.length ?? 0} stays</span></div>{properties?.length ? <div className="property-grid">{properties.map((property) => <button className="property-card" key={property._id} onClick={() => onSelect(property._id)}><div className="property-image">{property.type}</div><div className="property-info"><span className="eyebrow">{property.segment ?? 'Curated stay'}</span><h3>{property.name}</h3><p>{property.area} · {property.city}</p><strong>View rooms →</strong></div></button>)}</div> : <EmptyState title="Curated stays are coming soon" text="We are currently onboarding properties in Greater Yogyakarta. Check back soon or explore another destination." />}</main>; }

function HotelDetail({ propertyId, onBack, onRooms }: { propertyId: string | null; onBack: () => void; onRooms: () => void }) { const property = useQuery(api.properties.get, propertyId ? { id: propertyId as never } : 'skip'); if (!property) return <main className="page"><button className="back-button" onClick={onBack}>← Back</button><EmptyState title="Select a property" text="Choose a stay from search results to view its details." /></main>; return <main className="page"><button className="back-button" onClick={onBack}>← Search results</button><div className="detail-hero"><div className="detail-image">{property.type}</div><div><p className="eyebrow">{property.segment ?? 'Curated stay'} · {property.area}</p><h2>{property.name}</h2><p className="muted">{property.description}</p><p className="muted">{property.address}, {property.city}</p><button onClick={onRooms}>See available rooms</button></div></div><div className="detail-grid"><InfoCard title="Curated with care" text="Property information and photos are reviewed by Menetap." /><InfoCard title="Transparent pricing" text="Your total price is shown before you book." /><InfoCard title="Around your stay" text="Add breakfast, transfers, and more at checkout." /></div></main>; }

function RoomSelection({ propertyId, onBack, onContinue }: { propertyId: string | null; onBack: () => void; onContinue: (id: string) => void }) { const rooms = useQuery(api.rooms.listForProperty, propertyId ? { propertyId: propertyId as never } : 'skip'); return <main className="page narrow"><button className="back-button" onClick={onBack}>← Property details</button><p className="eyebrow">Room selection</p><h2>Choose your room</h2>{rooms?.length ? rooms.map((room) => <div className="room-card" key={room._id}><div><span className="eyebrow">Available rate</span><h3>{room.name}</h3><p className="muted">Up to {room.maxGuests} guests · {room.amenities.join(' · ')}</p></div><div className="room-price"><strong>Rp 850.000</strong><span>per night</span><button onClick={() => onContinue(room._id)}>Choose room</button></div></div>) : <EmptyState title="Rooms are not available yet" text="This property is still preparing its room inventory." />}</main>; }

function Checkout({ propertyId, roomTypeId, search, onBack, onComplete }: { propertyId: string | null; roomTypeId: string | null; search: SearchState; onBack: () => void; onComplete: (code: string) => void }) { const createBooking = useMutation(api.bookings.create); const [name, setName] = useState(''); const [email, setEmail] = useState(''); const [error, setError] = useState(''); const submit = async () => { if (!propertyId || !roomTypeId || !name || !email) { setError('Please provide your name and email.'); return; } try { const result = await createBooking({ propertyId: propertyId as never, roomTypeId: roomTypeId as never, checkIn: search.checkIn || new Date().toISOString().slice(0, 10), checkOut: search.checkOut || new Date(Date.now() + 86400000).toISOString().slice(0, 10), guestCount: search.guests, guestName: name, guestEmail: email, paymentMethod: 'pay_at_hotel' }); onComplete(result.reference); } catch (err) { setError(err instanceof Error ? err.message : 'Unable to create booking.'); } }; return <main className="page narrow"><button className="back-button" onClick={onBack}>← Room selection</button><p className="eyebrow">Checkout</p><h2>Complete your booking</h2><div className="checkout-grid"><div className="form-card"><label>Full name<input value={name} onChange={(e) => setName(e.target.value)} placeholder="Your name" /></label><label>Email<input value={email} onChange={(e) => setEmail(e.target.value)} type="email" placeholder="you@example.com" /></label><label>Phone number<input placeholder="+62" /></label><label className="check-row"><input type="checkbox" /> Add breakfast and airport transfer options after booking</label>{error && <p className="error-text">{error}</p>}<button onClick={submit}>Confirm booking</button></div><aside className="summary-card"><span className="eyebrow">Your stay</span><h3>Greater Yogyakarta</h3><p className="muted">{search.checkIn || 'Your check-in'} → {search.checkOut || 'Your check-out'}</p><div className="summary-line"><span>Room × 1 night</span><strong>Rp 850.000</strong></div><div className="summary-line total"><span>Total at hotel</span><strong>Rp 850.000</strong></div><small>Pay at hotel. No payment gateway required for this MVP.</small></aside></div></main>; }

function Confirmation({ code, onHome }: { code: string | null; onHome: () => void }) { const booking = useQuery(api.bookings.getByReference, code ? { reference: code } : 'skip'); return <main className="page narrow centered"><div className="success-icon">✓</div><p className="eyebrow">Booking confirmed</p><h2>Your stay is ready.</h2><p className="muted">We have saved your reservation. Your confirmation code is <strong>{code}</strong>.</p><div className="confirmation-card"><span>{booking ? `${booking.checkIn} → ${booking.checkOut}` : 'Greater Yogyakarta'}</span><strong>{booking?.paymentMethod === 'pay_at_hotel' ? 'Pay at hotel' : 'Manual bank transfer'}</strong><small>Menetap support will be here if you need anything.</small></div><button onClick={onHome}>Explore more stays</button></main>; }
function FeatureCard({ title, text }: { title: string; text: string }) { return <article className="info-card"><h3>{title}</h3><p>{text}</p></article>; }
function InfoCard({ title, text }: { title: string; text: string }) { return <article className="info-card"><h3>{title}</h3><p>{text}</p></article>; }
function EmptyState({ title, text }: { title: string; text: string }) { return <div className="empty-state"><h3>{title}</h3><p>{text}</p></div>; }
