import type { ComponentType } from 'react';

type CityDestination = {
  city: string;
  headline: string;
  intro: string;
  areas: Array<[string, string]>;
  properties: Array<[string, string, string]>;
  faqs: Array<[string, string]>;
};

const cities: Record<string, CityDestination> = {
  jakarta: { city: 'Jakarta', headline: 'City energy, neighborhood character, and stays close to what matters.', intro: 'Explore Jakarta through distinct urban neighborhoods, from heritage streets and creative districts to business hubs and coastal escapes.', areas: [['Menteng', 'Tree-lined streets, galleries, and a central base with a quieter rhythm.'], ['Kota Tua', 'Historic architecture, museums, and Jakarta’s old trading quarter.'], ['Sudirman', 'Business towers, dining, and practical access across the city.'], ['Kemang', 'Creative spaces, restaurants, and an easy evening scene.']], properties: [['Menteng Heritage House', 'Menteng · central leafy neighborhood', 'Heritage stay'], ['Kota Tua City Rooms', 'Kota Tua · historic district', 'City hotel'], ['Sudirman Skyline Suites', 'Sudirman · business district', 'City suites']], faqs: [['Which Jakarta area is best for a first visit?', 'Menteng is a comfortable central base, while Kota Tua suits guests who want history and museums close by.'], ['Is this page for Jakarta city?', 'Yes. This guide focuses on neighborhoods within Jakarta city rather than the wider Greater Jakarta region.']] },
  malang: { city: 'Malang', headline: 'Cooler days, creative cafés, and a gentle city pace.', intro: 'Malang is a relaxed base for highland escapes, heritage streets, and easy local food adventures.', areas: [['Klojen', 'Walkable cafés, heritage streets, and Malang’s lively city center.'], ['Batu', 'Mountain air, family attractions, and green weekend escapes.'], ['Ijen Boulevard', 'Tree-lined avenues, colonial character, and a quieter central stay.']], properties: [['Klojen City House', 'Klojen · central cafés nearby', 'Boutique stay'], ['Batu Highland Villa', 'Batu · mountain views', 'Villa'], ['Ijen Heritage Hotel', 'Ijen Boulevard · leafy streets', 'Heritage hotel']], faqs: [['Which area is best for a first Malang visit?', 'Klojen keeps you close to cafés, heritage streets, and the city’s everyday rhythm.'], ['Is Batu part of Malang?', 'Batu is a separate city in the Malang area, known for cooler air and highland attractions.']] },
  surabaya: { city: 'Surabaya', headline: 'Big-city energy, heritage quarters, and food worth travelling for.', intro: 'Surabaya pairs a practical urban base with historic streets, waterfront walks, and a deep local food culture.', areas: [['Tunjungan', 'The city’s classic boulevard, shopping, dining, and evening energy.'], ['Darmo', 'Shady avenues, museums, and a more residential central-Surabaya feel.'], ['Kenjeran', 'Coastal air, open views, and a different side of the city.']], properties: [['Tunjungan Grand Hotel', 'Tunjungan · central boulevard', 'City hotel'], ['Darmo Garden Residence', 'Darmo · leafy city base', 'Residence'], ['Kenjeran Coast Stay', 'Kenjeran · near the waterfront', 'Guesthouse']], faqs: [['Where should I stay in Surabaya for a first trip?', 'Tunjungan is a convenient first base for central attractions, restaurants, and transport connections.'], ['What is Surabaya known for?', 'Surabaya is known for its historic neighborhoods, bold local food, and role as East Java’s major urban gateway.']] },
  denpasar: { city: 'Denpasar', headline: 'Local Bali, market mornings, and a gateway to the island.', intro: 'Choose Denpasar for everyday Balinese life, traditional markets, cultural landmarks, and practical access across southern Bali.', areas: [['Sanur', 'Calmer beach mornings, local dining, and an easygoing coastal rhythm.'], ['Renon', 'Open civic spaces, museums, and a convenient central base.'], ['Kesiman', 'Temple culture, traditional neighborhoods, and a more local atmosphere.']], properties: [['Sanur Morning House', 'Sanur · beach access nearby', 'Guesthouse'], ['Renon City Suites', 'Renon · central Denpasar', 'City suites'], ['Kesiman Garden Stay', 'Kesiman · local neighborhood', 'Garden stay']], faqs: [['Is Denpasar a good base for Bali?', 'Denpasar works well for guests who want local city life and practical access to Sanur, the airport, and southern Bali.'], ['Which Denpasar area feels most relaxed?', 'Sanur offers the most relaxed coastal rhythm, while Kesiman feels more residential and locally rooted.']] },
  semarang: { city: 'Semarang', headline: 'Old-town character, hillside views, and a generous food scene.', intro: 'Semarang brings together Dutch-era architecture, coastal city life, hillside neighborhoods, and a distinct Central Java food culture.', areas: [['Kota Lama', 'Restored heritage buildings, galleries, and atmospheric evening walks.'], ['Simpang Lima', 'Central shopping, dining, and easy city connections.'], ['Gajahmungkur', 'Hillside air, city views, and a quieter residential base.']], properties: [['Kota Lama Heritage Stay', 'Kota Lama · old-town streets', 'Heritage stay'], ['Simpang Lima City Hotel', 'Simpang Lima · central location', 'City hotel'], ['Gajahmungkur Hillside House', 'Gajahmungkur · elevated city views', 'Guesthouse']], faqs: [['What is Semarang best known for?', 'Semarang is known for Kota Lama, coastal trading history, Central Javanese food, and its distinctive mix of old and new neighborhoods.'], ['Where is best for a weekend in Semarang?', 'Kota Lama is ideal for heritage walks, while Simpang Lima is practical for dining and central access.']] }
};

export function CityDestinationLanding({ slug, language, setLanguage, Footer }: { slug: string; language: 'EN' | 'ID'; setLanguage: (language: 'EN' | 'ID') => void; Footer: ComponentType<{ language: 'EN' | 'ID'; setLanguage: (language: 'EN' | 'ID') => void }> }) { const data = cities[slug]; if (!data) return null; const prefix = `/${language.toLowerCase()}`; return <><main className="destination-landing page"><p className="eyebrow">Explore {data.city}</p><h1>{data.headline}</h1><p className="destination-intro">{data.intro}</p><div className="destination-actions"><a href={`${prefix}/stays?destination=${encodeURIComponent(data.city)}`}>Explore {data.city} stays</a><a href={`${prefix}/destinations/all`}>All destinations</a></div><section className="destination-area-section"><div className="section-heading"><div><p className="eyebrow">Stay by area</p><h2>Find your {data.city} base</h2></div></div><div className="destination-area-grid">{data.areas.map(([name, description]) => <a className="destination-area-card" href={`${prefix}/stays?destination=${encodeURIComponent(name)}`} key={name}><strong>{name}</strong><p>{description}</p><span>Browse {name} stays →</span></a>)}</div></section><section className="destination-properties"><div className="section-heading"><div><p className="eyebrow">Places to start</p><h2>Properties to compare</h2></div><a href={`${prefix}/stays?destination=${encodeURIComponent(data.city)}`}>See all {data.city} stays →</a></div><div className="destination-property-grid">{data.properties.map(([name, location, type]) => <article key={name}><div className="property-image">{type}</div><div><h3>{name}</h3><p>{location}</p><a href={`${prefix}/stays?destination=${encodeURIComponent(data.city)}`}>View availability →</a></div></article>)}</div></section><section className="destination-faq"><p className="eyebrow">{data.city} travel questions</p><h2>Plan the practical details</h2>{data.faqs.map(([question, answer]) => <details key={question}><summary>{question}</summary><p>{answer}</p></details>)}<details><summary>Can I compare {data.city} stays by dates?</summary><p>Yes. Set your dates and guest count in the stays search to compare live availability and prices.</p></details></section><nav className="destination-internal-links" aria-label={`${data.city} travel links`}><a href={`${prefix}/destinations/all`}>All destinations</a><a href={`${prefix}/stays?destination=${encodeURIComponent(data.city)}`}>All {data.city} stays</a>{data.areas.map(([name]) => <a href={`${prefix}/stays?destination=${encodeURIComponent(name)}`} key={name}>{name} stays</a>)}</nav></main><Footer language={language} setLanguage={setLanguage} /></>; }
