import { useState } from "react";
import { CalendarCheck, Compass, Footprints, Map, Mountain, Palette, Search, Star, Utensils, Waves } from "lucide-react";
import { Button } from "./components/Button";

const categories = [["Tours & sightseeing", Map], ["Food & drink", Utensils], ["Outdoor & adventure", Mountain], ["Culture & workshops", Palette], ["Water activities", Waves]] as const;
const experiences = [["Ubud", "Sunrise trek up Mount Batur with local guide", Mountain, "4.9", "Rp 350K"], ["Yogyakarta", "Batik-making workshop with a master artisan", Palette, "4.8", "Rp 220K"], ["Bali", "Balinese cooking class & market tour", Utensils, "4.9", "Rp 280K"], ["Labuan Bajo", "Komodo Island snorkeling day trip", Waves, "4.7", "Rp 650K"]] as const;
const faqs = [["Can I cancel a booked experience?", "Yes — most experiences offer free cancellation up to 24 hours before the start time. Check each listing for its specific policy."], ["Are the hosts verified?", "Every host is reviewed and verified by Menetap before their experience is listed, including local permits where required."], ["Do I need to book in advance?", "Popular experiences fill up fast, especially on weekends — we recommend booking at least 2–3 days ahead."], ["Can I combine an experience with my stay booking?", "Yes, you can add experiences to an existing stay booking or book them separately — both earn Menetap Rewards points."]];

export function ExperiencesLanding() {
  const [open, setOpen] = useState<number | null>(null);
  return <main className="experiences-dc"><header className="experiences-dc-header"><div><a className="experiences-dc-brand" href="/en">menetap<span>.</span></a><nav><a href="/en/stays">Stays</a><a href="/en/rentals">Rentals</a><a className="active" href="/en/experiences">Experiences</a><a href="/en/rewards">Rewards</a></nav><div><a href="/en">Log in</a><a className="experiences-dc-join" href="/en">Join free</a></div></div></header><div className="experiences-dc-wrap">
    <section className="experiences-dc-hero"><div className="experiences-dc-badge"><Compass size={14}/>500+ local experiences across Indonesia</div><h1>Things to do, led by people who actually live there.</h1><p>Book tours, workshops, and activities hosted by local guides — from volcano sunrise treks to Balinese cooking classes. Free cancellation up to 24 hours before.</p><div><Button href="/en/experiences">Browse experiences</Button><Button href="/en/partners" variant="outline">Host an experience</Button></div></section>
    <section className="experiences-dc-section"><h2>Browse by category</h2><div className="experiences-dc-categories">{categories.map(([name, Icon])=><a href={`/en/experiences?category=${encodeURIComponent(name)}`} key={name}><span><Icon size={20}/></span><b>{name}</b></a>)}</div></section>
    <section className="experiences-dc-section"><div className="experiences-dc-heading"><h2>Popular right now</h2><a href="/en/experiences">See all experiences →</a></div><div className="experiences-dc-grid">{experiences.map(([city,title,Icon,rating,price],i)=><a href={`/en/experiences/detail?id=${i}`} key={title}><div className="experiences-dc-photo"><Icon size={26}/></div><div><small>{city}</small><h3>{title}</h3><span><Star size={12}/> {rating}</span><b>{price}</b></div></a>)}</div></section>
    <section className="experiences-dc-section"><h2>How it works</h2><div className="experiences-dc-how">{[["1. Find your experience", "Filter by city, category, or date to find something led by a verified local host.", Search], ["2. Book your spot", "Reserve instantly online — free cancellation up to 24 hours before start time.", CalendarCheck], ["3. Show up and go", "Meet your host at the listed point — everything else is arranged for you.", Footprints]].map(([title,body,Icon])=><article key={title as string}><Icon size={18}/><b>{title as string}</b><p>{body as string}</p></article>)}</div></section>
    <section className="experiences-dc-section"><h2>Frequently asked</h2><div className="experiences-dc-faqs">{faqs.map(([question,answer],i)=><article key={question}><button type="button" onClick={()=>setOpen(open===i?null:i)}><span>{question}</span><b>{open===i?"−":"+"}</b></button>{open===i&&<p>{answer}</p>}</article>)}</div></section>
    <section className="experiences-dc-cta"><div><h2>Ready to explore something new?</h2><p>Book a local experience in minutes — pair it with your next stay.</p></div><Button href="/en/experiences">Browse experiences</Button></section>
  </div><footer className="experiences-dc-footer"><div className="experiences-dc-footer-inner"><span>© 2026 Menetap. All rights reserved.</span><span>Managed by <a href="https://upscale.asia">UPSCALE</a></span></div></footer></main>;
}
