import { useState } from "react";
import { Bike, Car, MapPin, Receipt, ShieldCheck, Truck, UserCheck } from "lucide-react";
import { Button } from "./components/Button";

export function RentalsV2() {
  const [pickup, setPickup] = useState("Yogyakarta");
  const [pickupDate, setPickupDate] = useState("2026-10-12");
  const [returnDate, setReturnDate] = useState("2026-10-15");
  const vehicles = [["Honda Beat", "Automatic, 110cc. Helmet included.", "Rp 65,000/day", "8", "bike"], ["Yamaha NMAX", "Automatic, 155cc. Great for longer rides.", "Rp 95,000/day", "4", "bike"], ["Honda Scoopy", "Automatic, 110cc. Two helmets included.", "Rp 70,000/day", "6", "bike"], ["Toyota Avanza", "Self-drive, 7-seat MPV, insurance included.", "Rp 380,000/day", "3", "car"], ["Toyota Innova", "With driver, 7-seat, ideal for full-day trips.", "Rp 550,000/day", "2", "car"], ["Toyota Agya", "Self-drive, 5-seat city car, fuel-efficient.", "Rp 320,000/day", "5", "car"]];
  const search = () => window.location.assign(`/en/rentals/search?pickup=${encodeURIComponent(pickup)}&pickupDate=${pickupDate}&returnDate=${returnDate}`);
  return <main className="rentals-v2"><header className="rentals-v2-header"><div><a className="rentals-v2-brand" href="/en">menetap<span>.</span><b><MapPin size={11}/>rentals</b></a><nav><a href="/en/stays">Stays</a><a className="active" href="/en/rentals">Rentals</a><a href="/en/experiences">Experiences</a></nav><a href="/en">Log in</a></div></header><section className="rentals-v2-hero"><div className="rentals-v2-wrap"><div className="eyebrow"><Car size={14}/> Menetap-managed fleet</div><h1>Your ride is waiting the moment you land.</h1><p>Scooters and cars delivered to your hotel or the airport, with transparent pricing — no deposit surprises at pickup.</p><div className="rentals-v2-stats"><span><b>4.7★</b>Average rating</span><span><b>12,000+</b>Rentals completed</span><span><b>40+</b>Pickup spots</span></div></div></section><section className="rentals-v2-wrap rentals-v2-search"><label>Pickup<input value={pickup} onChange={e=>setPickup(e.target.value)} placeholder="City, hotel, airport"/></label><label>Pickup date<input type="date" value={pickupDate} onChange={e=>setPickupDate(e.target.value)}/></label><label>Return date<input type="date" value={returnDate} onChange={e=>setReturnDate(e.target.value)}/></label><Button onClick={search}>Search</Button></section><section className="rentals-v2-wrap rentals-v2-fleet"><h2>Available now in Yogyakarta</h2><p>Real-time availability for your selected dates</p>{[["Motorbikes", "bike"],["Cars", "car"]].map(([title,type])=><div key={type}><div className="rentals-v2-fleet-heading">{type==='bike'?<Bike size={16}/>:<Car size={16}/>}<h3>{title}</h3><a href={`/en/rentals/search?type=${type==='bike'?'scooter':'car'}`}>See all {title.toLowerCase()} →</a></div><div className="rentals-v2-grid">{vehicles.filter(v=>v[4]===type).map(([name,desc,price,available,kind])=><a href={`/en/rentals/search?type=${kind==='bike'?'scooter':'car'}`} key={name}><div className="rentals-v2-image">{kind==='bike'?<Bike size={26}/>:<Car size={26}/>}</div><div><b>{name}</b><small>{available} left</small><p>{desc}</p><strong>{price}</strong></div></a>)}</div></div>)}</section><section className="rentals-v2-wrap rentals-v2-trust"><span><ShieldCheck/>Insurance included</span><span><Truck/>Free delivery</span><span><Receipt/>No hidden fees</span><span><UserCheck/>Driver optional</span></section><section className="rentals-v2-wrap rentals-v2-cta"><div><h2>Already have a Menetap stay booked?</h2><p>Add a rental to your existing trip — delivered to your hotel on arrival day.</p></div><Button href="/en/my-trips">Add to my trip</Button></section></main>;
}
